# suspend does not work with the shim kernel, so lock the screen instead
[Login]
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=lock
HandleLidSwitchExternalPower=lock
HandleLidSwitchDocked=ignore
IdleAction=ignore
