# Make the touchpad behave like it does on Chrome OS: tap to click, and a
# two finger click for right click (instead of clicking in a corner).
Section "InputClass"
	Identifier "reshimboot touchpad"
	MatchIsTouchpad "on"
	MatchDriver "libinput"
	Option "Tapping" "on"
	Option "TappingButtonMap" "lrm"
	Option "ClickMethod" "clickfinger"
	Option "DisableWhileTyping" "on"
EndSection
